import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'en' | 'pt';

const PT: Record<string, string> = {
  // --- Login ---
  'Welcome back': 'Bem-vindo de volta',
  'Sign in to your account': 'Faça login na sua conta',
  'Email': 'E-mail',
  'Password': 'Senha',
  'Remember me': 'Lembrar de mim',
  'Forgot password?': 'Esqueceu sua senha?',
  'Sign In': 'Entrar',
  'Sign up': 'Inscrever-se',
  // --- Sidebar ---
  'Dashboard': 'Painel',
  'Flow Editor': 'Editor de fluxo',
  'History': 'Histórico',
  'Execution History': 'Histórico de Execução',
  'Settings': 'Configurações',
  'Logout': 'Sair',
  'Log out': 'Sair',
  // --- Dashboard ---
  'My Flows': 'Meus fluxos',
  'Quick Start': 'Início rápido',
  'Create New Flow': 'Criar novo fluxo',
  'New Flow': 'Novo fluxo',
  'No flows yet': 'Ainda não há fluxos',
  'Create your first automation flow': 'Crie seu primeiro fluxo de automação',
  'Total Flows': 'Fluxos totais',
  'Active': 'Ativo',
  'Total Executions': 'Total de execuções',
  'Draft': 'Rascunho',
  'Inactive': 'Inativo',
  'active': 'ativo',
  'inactive': 'inativo',
  'draft': 'rascunho',
  'Edit': 'Editar',
  'Delete': 'Excluir',
  'Are you sure?': 'Tem certeza?',
  'blocks': 'blocos',
  'executions': 'execuções',
  // --- Flow Editor ---
  'Blocks': 'Blocos',
  'Click to add & auto-connect': 'Clique para adicionar e conectar automaticamente',
  'Search blocks...': 'Buscar blocos...',
  'All': 'Todos',
  'Triggers': 'Gatilhos',
  'Logic': 'Lógica',
  'Actions': 'Ações',
  'Output': 'Saída',
  'Start building your flow': 'Comece a construir seu fluxo',
  'Pick blocks from the left panel — they auto-connect!': 'Escolha os blocos no painel esquerdo – eles se conectam automaticamente!',
  'Drag canvas to pan': 'Arraste a tela para deslocar',
  'Scroll to zoom': 'Role para ampliar',
  'Save': 'Salvar',
  'Run': 'Executar',
  'Running...': 'Executando...',
  'Unsaved': 'Não salvo',
  'Saved': 'Salvo',
  'links': 'links',
  'Properties': 'Propriedades',
  'Label': 'Nome',
  'Block Type': 'Tipo de bloco',
  'Configuration': 'Configuração',
  'Duplicate': 'Duplicar',
  'Back': 'Voltar',
  // --- Block Categories ---
  'trigger': 'gatilho',
  'logic': 'lógica',
  'action': 'ação',
  'output': 'saída',
  // --- Block Names ---
  'Manual Trigger': 'Gatilho Manual',
  'Webhook': 'Webhook',
  'Schedule': 'Agendamento',
  'If / Else': 'Se / Senão',
  'Delay': 'Atraso',
  'Set Variable': 'Definir variável',
  'Filter': 'Filtro',
  'HTTP Request': 'Requisição HTTP',
  'Slack': 'Slack',
  'Discord': 'Discord',
  'Telegram': 'Telegram',
  'OpenAI (ChatGPT)': 'OpenAI (ChatGPT)',
  'GitHub Issue': 'Issue no GitHub',
  'Send Webhook': 'Enviar webhook',
  'Transform Data': 'Transformar dados',
  'Run JavaScript': 'Executar JavaScript',
  'Console Log': 'Log no Console',
  'Notification': 'Notificação',
  'Alert Dialog': 'Diálogo de Alerta',
  'Save to Storage': 'Salvar no armazenamento',
  // --- Block Descriptions ---
  'Start the flow manually with a click': 'Inicie o fluxo manualmente com um clique',
  'Trigger via incoming HTTP request': 'Acionar por meio de solicitação HTTP recebida',
  'Run on a timed interval': 'Execute em um intervalo cronometrado',
  'Branch based on a condition': 'Ramificação com base em uma condição',
  'Wait before continuing': 'Espere antes de continuar',
  'Store a value for later steps': 'Armazene um valor para etapas posteriores',
  'Stop flow if condition is not met': 'Interrompa o fluxo se a condição não for atendida',
  'Make a real HTTP request to any URL': 'Faça uma solicitação HTTP real para qualquer URL',
  'Send a message to Slack via webhook': 'Envie uma mensagem para o Slack via webhook',
  'Send a message to Discord via webhook': 'Envie uma mensagem para o Discord via webhook',
  'Send a message via Telegram Bot API': 'Envie uma mensagem via Telegram Bot API',
  'Generate text with GPT models': 'Gere texto com modelos GPT',
  'Create an issue on a GitHub repository': 'Crie um problema em um repositório GitHub',
  'POST data to any webhook endpoint': 'POST dados para qualquer endpoint de webhook',
  'Map and transform data between steps': 'Mapeie e transforme dados entre etapas',
  'Execute custom JavaScript code': 'Execute código JavaScript personalizado',
  'Log data to browser console': 'Registrar dados no console do navegador',
  'Show a real browser notification': 'Mostrar uma notificação real do navegador',
  'Show a browser alert with data': 'Mostrar um alerta do navegador com dados',
  'Save data to browser localStorage': 'Salvar dados no navegador localStorage',
  // --- Block Property Labels ---
  'Input Payload (JSON)': 'Carga útil de entrada (JSON)',
  'Method': 'Método',
  'Sample Payload (JSON)': 'Exemplo de carga útil (JSON)',
  'Interval': 'Intervalo',
  'Payload (JSON)': 'Carga útil (JSON)',
  'Field path': 'Caminho do campo',
  'Operator': 'Operador',
  'Compare value': 'Comparar valor',
  'Delay (seconds)': 'Atraso (segundos)',
  'Variable name': 'Nome da variável',
  'Value': 'Valor',
  'Expected value': 'Valor esperado',
  'URL': 'URL',
  'Headers (JSON)': 'Cabeçalhos (JSON)',
  'Body (JSON)': 'Corpo (JSON)',
  'Webhook URL': 'URL do webhook',
  'Message': 'Mensagem',
  'Channel override': 'Substituição de canal',
  'Bot name': 'Nome do bot',
  'Avatar URL': 'URL do avatar',
  'Bot Token': 'Token de bot',
  'Chat ID': 'ID do chat',
  'Parse mode': 'Modo de parse',
  'API Key': 'Chave de API',
  'Model': 'Modelo',
  'Prompt': 'Prompt',
  'System prompt': 'Prompt de sistema',
  'Temperature (0-2)': 'Temperatura (0-2)',
  'Personal Access Token': 'Token de acesso pessoal',
  'Repository (owner/repo)': 'Repositório (proprietário/repo)',
  'Issue title': 'Título da issue',
  'Issue body': 'Corpo da issue',
  'Labels (comma-separated)': 'Rótulos (separados por vírgula)',
  'Send previous step data?': 'Enviar dados da etapa anterior?',
  'Custom body (JSON)': 'Corpo personalizado (JSON)',
  'JavaScript Expression': 'Expressão JavaScript',
  'Code': 'Código',
  'Log label': 'Label do log',
  'What to log': 'O que logar',
  'Title': 'Título',
  'Include data?': 'Incluir dados?',
  'Storage key': 'Chave de armazenamento',
  'What to save': 'O que salvar',
  'Enabled': 'Ativado',
  'Disabled': 'Desativado',
  // --- Execution History ---
  'All Executions': 'Todas as execuções',
  'No executions yet': 'Ainda não há execuções',
  'Run a flow to see execution history here': 'Execute um fluxo para ver o histórico de execução aqui',
  'Success': 'Sucesso',
  'Failed': 'Falhou',
  'success': 'sucesso',
  'failed': 'falhou',
  'skipped': 'pulado',
  'running': 'executando',
  'Steps': 'Etapas',
  'Duration': 'Duração',
  'Started': 'Iniciado',
  'Completed': 'Concluído',
  'Error': 'Erro',
  'Execution Details': 'Detalhes de execução',
  'Step': 'Etapa',
  // --- Templates ---
  'Fetch & Notify': 'Buscar e notificar',
  'Fetch data from an API and show a browser notification': 'Busque dados de uma API e mostre uma notificação do navegador',
  'Conditional Logic': 'Lógica Condicional',
  'Fetch data, check a condition, then act accordingly': 'Busque dados, verifique uma condição e aja de acordo',
  'Blank Flow': 'Fluxo em branco',
  'Start from scratch': 'Comece do zero',
  // --- Toasts ---
  'Flow saved': 'Fluxo salvo',
  'Flow not found': 'Fluxo não encontrado',
  'Add a Trigger block to run the flow': 'Adicione um bloco Trigger para executar o fluxo',
  'Already connected': 'Já conectado',
  'Connected': 'Conectado',
  'Flow deleted': 'Fluxo excluído',
  // --- Extra UI ---
  'Sign out': 'Sair',
  'Signing in...': 'Fazendo login...',
  'Sign in': 'Entrar',
  'Visual automation made simple': 'Automação visual simplificada',
  'Drag & Drop Builder': 'Construtor de arrastar e soltar',
  'Create automations visually with intuitive blocks': 'Crie automações visualmente com blocos intuitivos',
  'Smart Connections': 'Conexões inteligentes',
  'Link triggers, conditions, actions & notifications': 'Conecte gatilhos, condições, ações e notificações',
  'Track every run with detailed logs and status': 'Acompanhe cada execução com registros e status detalhados',
  'Sign in to your account to continue': 'Faça login em sua conta para continuar',
  'Start free trial': 'Iniciar teste gratuito',
  'Overview of your automation flows': 'Visão geral dos seus fluxos de automação',
  'Templates': 'Templates',
  'Create from Template': 'Criar a partir de Template',
  'Active Flows': 'Fluxos Ativos',
  'Success Rate': 'Taxa de sucesso',
  'Your Flows': 'Seus fluxos',
  'No flows yet. Create one to get started!': 'Ainda não há fluxos. Crie um para começar!',
  'No description': 'Sem descrição',
  'runs': 'execuções',
  'Updated': 'Atualizado',
  'Deactivate': 'Desativar',
  'Activate': 'Ativar',
  'Recent Executions': 'Execuções Recentes',
  'View all': 'Ver tudo',
  'No executions yet. Run a flow to see results here.': 'Ainda não há execuções. Execute um fluxo para ver os resultados aqui.',
  'Track and monitor your flow executions': 'Rastreie e monitore suas execuções de fluxo',
  'No blocks match your search': 'Nenhum bloco corresponde à sua pesquisa',
  'Execution ID': 'ID de execução',
  'Flow ID': 'ID do fluxo',
  'In progress': 'Em andamento',
  'Execution Logs': 'Registros de execução',
  'No executions match this filter': 'Nenhuma execução corresponde a este filtro',
  'Please enter your email': 'Por favor insira seu e-mail',
  'Please enter your password': 'Por favor digite sua senha',
  'Toggle block panel': 'Alternar painel de bloco',
  'Status': 'Status',
  'Flow': 'Fluxo',
};

@Injectable({ providedIn: 'root' })
export class TranslateService {
  lang = signal<Lang>((localStorage.getItem('flowlet-lang') as Lang) || 'en');

  isPt = computed(() => this.lang() === 'pt');

  setLang(lang: Lang): void {
    this.lang.set(lang);
    localStorage.setItem('flowlet-lang', lang);
  }

  toggle(): void {
    this.setLang(this.lang() === 'en' ? 'pt' : 'en');
  }

  t(key: string): string {
    if (this.lang() === 'en') return key;
    return PT[key] ?? key;
  }
}
